config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :employees, :logins

  root 'employees#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :hire, presence: true
    validates :code, presence: true, uniqueness: true
    validates :personal_email, presence: true, uniqueness: true
    validates :contact_number, presence: true, uniqueness: true
    validates :gender, presence: true

    mount_uploader :avatar, AvatarUploader

    protected
    
    def self.authenticate login, password
        return false if password.blank?

        ldap = Net::LDAP.new
        ldap.host = "172.16.10.10"
        ldap.port = 389
        ldap.base = "OU=barajounusers,DC=barajoun,DC=local"
        ldap.auth "#{login}@barajoun.local", password

        if ldap.bind
            puts "###ldap auth successful###"
            Employee.where({first_name: login}).first
        end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable, :rememberable, :trackable 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  include EmployeesHelper
  #helper_method :get_office_departments, :get_employee_status 

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :date_of_birth, :gender, :country, :personal_email, :contact_number, :code, :department, :status, :hire, :end_hire, :avatar)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  include EmployeesHelper
  require 'uri'

  def create
    if employee = Employee.authenticate(params[:login], params[:password])
      session[:employee_id] = employee.id

      puts "===session id set: session[:current_user_id]}==="
      session[:employee_first_name] = employee.first_name

      if get_admin_list.include?(employee.first_name)
          puts "===Employee is admin==="
          session[:admin] = true
          flash[:success] = "You have succesfully logged in and you ARE a web admin."
          redirect_to :back
      else
          puts "===Employee is not admin==="
          flash[:success] = "You have succesfully logged in and you're NOT a web admin."
          redirect_to :back
      end
    else
      puts "===Login failed==="
      flash[:alert] = "Login failed! Check your credentials again."
      redirect_to :back
    end
  end
  
  def destroy
    session[:employee_id] = nil
    session[:employee_first_name] = nil
    session[:admin] = nil

    puts Rails.application.routes.recognize_path(request.referrer)[:action]

    if Rails.application.routes.recognize_path(request.referrer)[:action] == "edit" 
      flash[:alert] = "You are being redirected to the main page as you're NOT allowed to edit information once you log out."
      redirect_to root_path
    else
      flash[:success] = "You've successfully logged out."
      redirect_to :back
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def get_employee_departments type
      prod = %w{Modeling Animation Rigging Lighting Texturing Compositing FX}
      tech = %w|Information\ Technology Pipeline|
      supp = %w"Administration Human\ Resources Production\ Support"
      all = prod + tech + supp

      if type.equal? :prod
          prod
      elsif type.equal? :tech 
          tech
      elsif type.equal? :supp
          supp
      else 
          deps = prod + tech + supp 
          deps.sort
      end
  end

  def get_employee_status
      status_list = ['Active', 'Inactive']
  end    

  def get_gender
      status_list = ['Male', 'Female']
  end    

  def get_admin_list
      admin_list = ['abegail', 'abhishek']
  end    
end

app/views/employees/_form.html.erb
<div class="row">
  <div class="well col-md-3">
    <%= form_for @employee, html: {role: "form", multipart: true} do |f| %>
      <% if @employee.errors.any? %>
        <div class="bg-danger" id="error_explanation">
          <h2>Fix the following <%= pluralize(@employee.errors.count, "error") %>:</h2>

          <ul>
          <% @employee.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <!-- Official Information -->
    <div class="panel-group" id="accordion">
      <div class="panel panel-default" id="panel1">
        <div class="panel-heading">
          <h4 class="panel-title">
              Official Information
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
          <div class="panel-body">
            <div class="form-group">
              <%= f.label :code %><br>
              <%= f.text_field :code, class: "form-control text-field-class" %>
            </div>
            <div class="form-group">
              <%= f.label :department %><br>
              <%= f.select :department, get_employee_departments(:all), include_blank: "Select department" %>
            </div>
            <div class="form-group">
              <%= f.label :status %><br>
              <%= f.select :status, get_employee_status, include_blank: "Select status" %>
            </div>
            <div class="form-group">
              <%= f.label :hire %><br>
              <%= f.date_select :hire, prompt: { day: 'Select day', month: 'Select Month', year: 'Select Year' }, order: [:day, :month, :year],  class: "selectpicker" %>
            </div>
            <div class="form-group" id="end_date">
              <%= f.label :end_hire %><br>
              <%= f.date_select :end_hire, disabled: false, prompt: { day: 'Select day', month: 'Select Month', year: 'Select Year' }, order: [:day, :month, :year] %>
            </div>
            <div class="form-group">
              <%= f.label :avatar %><br>
              <%= f.file_field :avatar %>
            </div>

          </div>
        </div>
      </div>
    </div>

    <!-- Personal Information -->
    <div class="panel-group" id="accordion">
      <div class="panel panel-default" id="panel2">
        <div class="panel-heading">
          <h4 class="panel-title">
              Personal Information
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
          <div class="panel-body">
            <div class="form-group">
              <%= f.label :first_name %><br>
              <%= f.text_field :first_name, class: "form-control text-field-class" %>
            </div>
            <div class="form-group">
              <%= f.label :last_name %><br>
              <%= f.text_field :last_name, class: "form-control text-field-class" %>
            </div>
            <div class="form-group">
              <%= f.label :date_of_birth %><br>
              <%= f.date_select :date_of_birth, prompt: { day: 'Select day', month: 'Select Month', year: 'Select Year' }, order: [:day, :month, :year], start_year: 1950, class: "form-control"  %>
            </div>
            <div class="form-group">
              <%= f.label :gender %><br>
              <%= f.select :gender, get_gender, include_blank: "Select gender" %>
            </div>
            <div class="form-group">
              <%= f.label :country %><br>
              <%= f.country_select :country, {priority: %w(US CA AE IN PK), prompt: 'Please select a country'}%>
            </div>
            <div class="form-group">
              <%= f.label :personal_email %><br>
              <%= f.text_field :personal_email, class: "form-control text-field-class" %>
            </div>
            <div class="form-group">
              <%= f.label :contact_number %><br>
              <%= f.text_field :contact_number, class: "form-control text-field-class" %>
            </div>
          </div>
        </div>
      </div>
    </div>
     
    <!-- Submit button -->
    <div class="actions form-group">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
 
  <div class="col-md-2">
    <div class="thumbnail">
      <img data-src="holder.js/100%x200" alt="Generic placeholder thumbnail">
    </div>  
  </div>
</div>

    <%= javascript_tag do %>
      $("#employee_status").on('change', function() {
          if($(this).val() == 'Inactive') {
              $("#employee_end_date_1i")[0].disabled=false;
              $("#employee_end_date_2i")[0].disabled=false;
              $("#employee_end_date_3i")[0].disabled=false;
          }
          else {
              $("#employee_end_date_1i")[0].disabled=true;
              $("#employee_end_date_2i")[0].disabled=true;
              $("#employee_end_date_3i")[0].disabled=true;
          }
      });
    <% end %>

app/views/employees/edit.html.erb
<div class="col-md-offset-4">
  <h3><strong>Update Employee</strong></h3>

  <%= render 'form' %>

  <%= link_to 'Show', @employee, class: "btn btn-primary" %> 
  <%= link_to 'Back', employees_path, class: "btn btn-primary" %>
</div>

app/views/employees/index.html.erb
<!--
<div class="row">
  <div class="jumbotron">
    <h1 class="welcome-message">Welcome to the Employee Application!</h1>
  </div>
  <div id="custom-search-input">
    <div class="input-group col-md-12">
      <input type="text" class="  search-query form-control" placeholder="Search" />
      <span class="input-group-btn">
        <button class="btn" type="button">
          <span class=" glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
  </div>
</div>
-->

<div class="row">
  <%= render 'layouts/sidebar' %>

  <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-1 main">

    <!-- flash message --> 
    <%= render 'layouts/flash' %>
    
    <% if session[:admin] %>
      <div class="new-employee">
        <%= link_to 'Create a new employee', new_employee_path, class: "btn btn-primary" %>
      </div>
    <% end %>

    <div class="row">
      <div class="bs-example">
        <% @employees.each do |employee| %>
          <div class="col-sm-6 col-md-3">
            <div class="thumbnail">
              <img data-src="holder.js/250x300" alt="Generic placeholder thumbnail">
              <div class="caption caption2">
                 <table class="employee-details">
                   <tbody class="employee-tbody">
                     <tr>
                       <td>
                          <strong><%= "#{employee.first_name} #{employee.last_name}".titleize %></strong>
                       </td>
                       <td>
                         <strong><%= employee.department %></strong>
                       </td>
                     </tr>
                     <tr>
                       <td>
                         <strong><%= employee.personal_email %></strong>
                       </td>
                       <td>
                         <strong><%= employee.contact_number %></strong>
                       </td>
                     </tr>
                   </tbody>
                 </table>
              </div>
              <div class="show-edit">
                <% unless session[:employee_id].blank? %>
                  <% if session[:admin] || session[:employee_id] == employee.id %>
                    <%= link_to 'Edit', edit_employee_path(employee), class: "btn btn-default btn-primary" %>
                  <% end %>
                <% end %>
                  <%= link_to 'Show', employee_path(employee.id), class: "btn btn-default btn-primary" %>
              </div>
            </div>
          </div>
        <% end %>
      </div><!-- /.bs-example -->
    </div>
  </div>

</div>

app/views/employees/new.html.erb
<div class="col-md-offset-4">
  <h3><strong>New Employee</strong></h3>

  <%= render 'form' %>

  <%= link_to 'Back', employees_path, class: "btn btn-info" %>
</div>

app/views/employees/show.html.erb
<div class="row">
  <div class="col-md-offset-4">
    <h3><strong class="">Employee Record: <%= "#{@employee.first_name} #{@employee.last_name}".titleize %></strong></h3>
    <div class="row">
      <div class="well col-md-4">


        <!-- Official Information -->
        <div class="panel-group" id="accordion">
          <div class="panel panel-default" id="panel1">
            <div class="panel-heading">
              <h4 class="panel-title">
                  Official Information
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
              <div class="panel-body">

                <table class="table">
                  <tbody>
                    <tr class="grey">
                      <td class="td-class"><strong class="a">Code:</strong></td>
                      <td><strong><%= @employee.code %></strong></td>
                    </tr>
                    <tr class="white">
                      <td class="td-class"><strong class="a">Department:</strong></td>
                      <td><strong><%= @employee.department %></strong></td>
                    </tr>
                    <tr class="grey">
                      <td class="td-class"><strong class="a">Status:</strong></td>
                      <td><strong><%= @employee.status %></strong></td>
                    </tr>
                    <tr class="white">
                      <td class="td-class"><strong class="a">Hire:</strong></td>
                      <td><strong><%= @employee.hire.strftime "%d-%m-%Y" %></strong></td>
                    </tr>
                    <% if @employee.end_hire? %>
                        <tr class="grey">
                          <td class="td-class"><strong class="a">EndHire:</strong></td>
                          <td><strong><%= @employee.end_hire.strftime "%d-%m-%Y" %></strong></td>
                        </tr>
                    <% end %>
                  </tbody>
                </table>

              </div>
            </div>
          </div>
        </div>

        <!-- Personal Information -->
        <div class="panel-group" id="accordion">
          <div class="panel panel-default" id="panel2">
            <div class="panel-heading">
              <h4 class="panel-title">
                  Personal Information
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
              <div class="panel-body">
                <table class="table">
                  <tbody>
                    <tr class="grey">
                      <td class="td-class"><strong class="a">First Name:</strong></td>
                      <td><strong class=" text-left"><%= @employee.first_name.titleize %></strong></td>
                    </tr>
                    <tr class="white">
                      <td class="td-class"><strong class="a">Last Name:</strong></td>
                      <td><strong class=" text-left"><%= @employee.last_name.titleize %></strong></td>
                    </tr>
                    <tr class="grey">
                      <td class="td-class"><strong class="a">Date Of Birth:</strong></td>
                      <td><strong class=" text-left"><%= @employee.date_of_birth.strftime("%d-%m-%Y") if @employee.date_of_birth? %></strong></td>
                    </tr>
                    <tr class="white">
                      <td class="td-class"><strong class="a">Gender:</strong></td>
                      <td><strong class=" text-left"><%= @employee.gender.titleize %></strong></td>
                    </tr>
                    <tr class="grey">
                      <td class="td-class"><strong class="a">Country:</strong></td>
                      <td><strong class=" text-left"><%= Carmen::Country.coded(@employee.country).name.titleize %></strong></td>
                    </tr>
                    <tr class="white">
                      <td class="td-class"><strong class="a">Email:</strong></td>
                      <td><strong class=" text-left"><%= @employee.personal_email %></strong></td>
                    </tr>
                    <tr class="grey">
                      <td class="td-class"><strong class="a">Contact Number:</strong></td>
                      <td><strong class=" text-left"><%= @employee.contact_number %></strong></td>
                    </tr>
                  </tbody>
                </table>

              </div>
            </div>
          </div>
        </div>


        <% unless session[:employee_id].blank? %>
          <% if session[:admin] || session[:employee_id] == @employee.id %>
            <%= link_to "Edit", edit_employee_path(@employee), class: "btn btn-primary" %>
          <% end %>
        <% end %>

        <%= link_to "Back", employees_path, class: "btn btn-primary" %><br>
      </div>
      <div class="col-md-2">
        <div class="thumbnail">
          <img data-src="holder.js/100%x200" alt="Generic placeholder thumbnail">
        </div>
      </div>
    </div>
  </div>
</div> 
<!--
           <%= link_to "Edit", edit_employee_path(@employee) %>
           <%= link_to "Back", employees_path %><br>
           <p class=" text-info">May 05,2014,03:00 pm </p>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= "#{@employee.first_name()} #{@employee.last_name()}" %></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-4 col-lg-4 " align="center">
              <% if @employee.avatar.present? %>
                <%= image_tag @employee.avatar_url(:profile) %>
              <% else %>
                <%= image_tag "https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100", alt: "User pic", class: "img-circle" %>
              <% end %>
            </div>
            <div class=" col-md-8 col-lg-8 "> 
              <table class="table table-user-information">
                <tbody>
                  <tr>
                    <td>First Name:</td>
                    <td><%= @employee.first_name %></td>
                  </tr>
                  <tr>
                    <td>Last Name:</td>
                    <td><%= @employee.last_name %></td>
                  </tr>
                  <tr>
                    <td>Date Of Birth:</td>
                    <td><%= @employee.date_of_birth %></td>
                  </tr>
                  <tr>
                    <td>Gender:</td>
                    <td><%= @employee.gender %></td>
                  </tr>
                  <tr>
                    <td>Country:</td>
                    <td><%= Carmen::Country.coded(@employee.country).name %></td>
                  </tr>
                  <tr>
                    <td>E-mail:</td>
                    <td><%= @employee.personal_email %></td>
                  </tr>
                  <tr>
                    <td>Contact Number:</td>
                    <td><%= @employee.contact_number %></td>
                  </tr>  
                  <tr>
                    <td>Employee Code:</td>
                    <td><%= @employee.code %></td>
                  </tr>  
                  <tr>
                    <td>Status:</td>
                    <td><%= @employee.status %></td>
                  </tr>  
                  <tr>
                    <td>Department:</td>
                    <td><%= @employee.department %></td>
                  </tr>
                  <tr>
                    <td>Hire:</td>
                    <td><%= @employee.hire %></td>
                  </tr>
                  <tr>
                    <td>End Hire:</td>
                    <td><%= @employee.end_hire %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="panel-footer">
          <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
          <span class="pull-right">
            <a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
            <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
          </span>
        </div>
      </div>
    </div>
  </div>
-->

app/views/layouts/__search_nav_bar__.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Barajoun</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                  <li class="active"><a href="#">Link</a></li>
                  <li><a href="#">Link</a></li>
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                          <li><a href="#">Action</a></li>
                          <li><a href="#">Another action</a></li>
                          <li><a href="#">Something else here</a></li>
                          <li class="divider"></li>
                          <li><a href="#">Separated link</a></li>
                          <li class="divider"></li>
                          <li><a href="#">One more separated link</a></li>
                      </ul>
                  </li>
              </ul>
                
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="#">Link</a></li>
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                          <li><a href="#">Action</a></li>
                          <li><a href="#">Another action</a></li>
                          <li><a href="#">Something else here</a></li>
                          <li class="divider"></li>
                          <li><a href="#">Separated link</a></li>
                      </ul>
                  </li>
              </ul>

              <form class="navbar-form" role="search">
                  <div class="input-group">
                      <input type="text" class="form-control" placeholder="Search">
                      <span class="input-group-btn">
                          <button type="reset" class="btn btn-default">
                              <span class="glyphicon glyphicon-remove">
                                  <span class="sr-only">Close</span>
                              </span>
                          </button>
                          <button type="submit" class="btn btn-default">
                              <span class="glyphicon glyphicon-search">
                                  <span class="sr-only">Search</span>
                              </span>
                          </button>
                      </span>
                  </div>
              </form>
          </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| -%>
  <% next if name == "success" %>

  <div class="alert alert-error fade in my-alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4><%= "#{msg.titleize}" %>
  </div>
<% end -%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand navbar-brand-row" href="#">Barajoun Studios</a>
      <ul class="nav navbar-nav navbar-right navbar-brand-row">
        <li><a href="#">Apps</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">About</a></li>
      </ul>
    </div>
   
    <div id="navbar" class="navbar-collapse collapse">
      <a class="navbar-brand-center" href="#">Employee Portal</a>

      <!-- form_tag RoR -->
      <% unless session[:employee_id]%>
          <%= form_tag logins_path, {method: "post", class: "navbar-form navbar-right"} do %>
            <%= text_field_tag :login, "", {class: "form-control login-form", placeholder: "Login"} %>
            <%= password_field_tag :password, "", {class: "form-control login-form", placeholder: "Password"} %>
            <%= submit_tag "Submit", class: "btn btn-primary" %>
            <%= %>
          <% end %>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Welcome #{session[:employee_first_name]}", "#", class: "login-name" %></li>
              <li><%= link_to "Logout", login_path(session[:employee_id]), method: "delete", class: "btn" %></li>
          </ul>
      <% end %>
      
      <!--
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control login-form" placeholder="Login">
        <input type="text" class="form-control login-form" placeholder="Password">
        <input type="submit" value="Login" class="btn btn-info">
      </form>
      -->
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-3 col-md-1 sidebar">
  <ul class="nav nav-sidebar">
    <li class="active"><%= link_to 'All', '#' %></li>
  </ul>

  <strong class='sidebar-subheader'>Production</strong>
  <ul class="nav nav-sidebar">
    <% get_employee_departments(:prod).each do |dept| %>
      <li class=""><%= link_to dept, '#' %></li>
    <% end %>
  </ul>

  <strong class='sidebar-subheader'>Technology</strong>
  <ul class="nav nav-sidebar">
    <% get_employee_departments(:tech).each do |dept| %>
      <li class=""><%= link_to dept, '#' %></li>
    <% end %>
  </ul>

  <strong class='sidebar-subheader'>Support</strong>
  <ul class="nav nav-sidebar">
    <% get_employee_departments(:supp).each do |dept| %>
      <li class=""><%= link_to dept, '#' %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container-fluid">

  <%= yield %>

</div>

</body>
</html>